"""Generate docs/js/playground.js with the pylookup source embedded."""
import pathlib

ROOT = pathlib.Path(r"c:\pylookup")
PKG = ROOT / "src" / "pylookup"
OUT = ROOT / "docs" / "js" / "playground.js"

FILES = ["__init__.py", "exceptions.py", "utils.py", "lookup.py", "filtering.py", "sorting.py"]


def js_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


entries = []
for name in FILES:
    src = (PKG / name).read_text(encoding="utf-8")
    entries.append(f'  "{name}": `{js_escape(src)}`')

files_obj = ",\n".join(entries)

template = r'''// Auto-generated by gen_playground_js.py — do not edit by hand.
// Regenerate after changing the library source.

const PYLOOKUP_FILES = {
__FILES__
};

const pgStatus = () => document.getElementById("pg-status");
const pgOutput = () => document.getElementById("pg-output");

const pyodideReady = (async () => {
  pgStatus().textContent = "Loading Python (first visit takes a few seconds)...";
  const pyodide = await loadPyodide();
  pyodide.FS.mkdir("/home/pyodide/pylookup");
  for (const [name, src] of Object.entries(PYLOOKUP_FILES)) {
    pyodide.FS.writeFile("/home/pyodide/pylookup/" + name, src);
  }
  pyodide.runPython('import sys; sys.path.insert(0, "/home/pyodide")');
  pgStatus().textContent = "Ready! Edit the code and press Run.";
  return pyodide;
})();

async function pgRun() {
  const out = pgOutput();
  out.textContent = "Running...";
  try {
    const pyodide = await pyodideReady;
    pyodide.globals.set("_user_code", document.getElementById("pg-code").value);
    const result = pyodide.runPython(`
import sys, io
_buf = io.StringIO()
_old = sys.stdout
sys.stdout = _buf
try:
    exec(_user_code, {})
finally:
    sys.stdout = _old
_buf.getvalue()
`);
    out.textContent = result || "(no output — use print() to see results)";
  } catch (e) {
    out.textContent = e.message;
  }
}

document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("pg-run").addEventListener("click", pgRun);
});
'''

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(template.replace("__FILES__", files_obj), encoding="utf-8")
print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
